local API=_G.QFXTalentData
if not API then return end
local manifest={
  apiVersion=2,
  dataVersion="2026.08.18.1816.34",
  minDisplayVersion="0.5.0",
  generatedAt="2026-08-18T18:16:34.793114+00:00",
  seasonName="MN Season 2",
  seasonSlug="season-mn-2",
  source="Raider.IO global Mythic+ rankings and Warcraft Logs global raid rankings",
  contentModules={
    mythicplus="QFXTalentData_MythicPlus",
    raidHeroic="QFXTalentData_RaidHeroic",
    raidMythic="QFXTalentData_RaidMythic",
  },
  specNames={
    [62]="Arcane Mage",
    [63]="Fire Mage",
    [64]="Frost Mage",
    [65]="Holy Paladin",
    [66]="Protection Paladin",
    [70]="Retribution Paladin",
    [71]="Arms Warrior",
    [72]="Fury Warrior",
    [73]="Protection Warrior",
    [102]="Balance Druid",
    [103]="Feral Druid",
    [104]="Guardian Druid",
    [105]="Restoration Druid",
    [250]="Blood Death Knight",
    [251]="Frost Death Knight",
    [252]="Unholy Death Knight",
    [253]="Beast Mastery Hunter",
    [254]="Marksmanship Hunter",
    [255]="Survival Hunter",
    [256]="Discipline Priest",
    [257]="Holy Priest",
    [258]="Shadow Priest",
    [259]="Assassination Rogue",
    [260]="Outlaw Rogue",
    [261]="Subtlety Rogue",
    [262]="Elemental Shaman",
    [263]="Enhancement Shaman",
    [264]="Restoration Shaman",
    [265]="Affliction Warlock",
    [266]="Demonology Warlock",
    [267]="Destruction Warlock",
    [268]="Brewmaster Monk",
    [269]="Windwalker Monk",
    [270]="Mistweaver Monk",
    [577]="Havoc Demon Hunter",
    [581]="Vengeance Demon Hunter",
    [1467]="Devastation Evoker",
    [1468]="Preservation Evoker",
    [1473]="Augmentation Evoker",
    [1480]="Devourer Demon Hunter",
  },
  raidDifficulties={
    [4]="Heroic",
    [5]="Mythic",
  },
  dungeons={
    {id=16865,slug="altar-of-fangs",names={enUS="Altar of Fangs"},aliases={"Altar of Fangs", "altar-of-fangs"}},
    {id=16368,slug="den-of-nalorakk",names={enUS="Den of Nalorakk"},aliases={"Den of Nalorakk", "den-of-nalorakk"}},
    {id=9526,slug="kings-rest",names={enUS="Kings' Rest"},aliases={"Kings' Rest", "kings-rest"}},
    {id=16091,slug="murder-row",names={enUS="Murder Row"},aliases={"Murder Row", "murder-row"}},
    {id=14063,slug="ruby-life-pools",names={enUS="Ruby Life Pools"},aliases={"Ruby Life Pools", "ruby-life-pools"}},
    {id=9527,slug="temple-of-sethraliss",names={enUS="Temple of Sethraliss"},aliases={"Temple of Sethraliss", "temple-of-sethraliss"}},
    {id=16359,slug="the-blinding-vale",names={enUS="The Blinding Vale"},aliases={"The Blinding Vale", "the-blinding-vale"}},
    {id=16425,slug="voidscar-arena",names={enUS="Voidscar Arena"},aliases={"Voidscar Arena", "voidscar-arena"}},
  },
  raids={
    {
      id=1307,slug="the-voidspire",names={enUS="The Voidspire", zhCN="虚影尖塔", zhTW="虛無之尖"},aliases={"the-voidspire", "The Voidspire", "虚影尖塔", "虛無之尖", "Voidspire"},
      bosses={
        {id=3176,slug="imperator-averzian",names={enUS="Imperator Averzian", zhCN="元首阿福扎恩", zhTW="元首阿弗茲安"}},
        {id=3177,slug="vorasius",names={enUS="Vorasius", zhCN="弗拉希乌斯", zhTW="沃拉修斯"}},
        {id=3179,slug="fallen-king-salhadaar",names={enUS="Fallen-King Salhadaar", zhCN="陨落之王萨哈达尔", zhTW="墮落之王薩哈達爾"}},
        {id=3178,slug="vaelgor-and-ezzorak",names={enUS="Vaelgor & Ezzorak", zhCN="威厄高尔和艾佐拉克", zhTW="維爾戈與艾佐拉克"}},
        {id=3180,slug="lightblinded-vanguard",names={enUS="Lightblinded Vanguard", zhCN="光盲先锋军", zhTW="盲光先鋒"}},
        {id=3181,slug="crown-of-the-cosmos",names={enUS="Crown of the Cosmos", zhCN="宇宙之冕", zhTW="宇宙之冠"}},
      },
    },
    {
      id=1314,slug="the-dreamrift",names={enUS="The Dreamrift", zhCN="梦境裂隙", zhTW="夢境裂隙"},aliases={"the-dreamrift", "The Dreamrift", "梦境裂隙", "夢境裂隙", "Dreamrift"},
      bosses={
        {id=3306,slug="chimaerus",names={enUS="Chimaerus, the Undreamt God", zhCN="奇美鲁斯，未梦之神", zhTW="奇美拉斯，未夢之神"}},
      },
    },
    {
      id=1308,slug="march-on-queldanas",names={enUS="March on Quel'Danas", zhCN="进军奎尔丹纳斯", zhTW="進軍奎爾達納斯"},aliases={"march-on-queldanas", "March on Quel'Danas", "进军奎尔丹纳斯", "進軍奎爾達納斯", "Quel'Danas"},
      bosses={
        {id=3182,slug="beloren-child-of-alar",names={enUS="Belo'ren, Child of Al'ar", zhCN="贝洛朗，奥的子嗣", zhTW="貝洛倫，歐爾之子"}},
        {id=3183,slug="midnight-falls",names={enUS="Midnight Falls", zhCN="至暗之夜降临", zhTW="午夜降臨"}},
      },
    },
    {
      id=2427,slug="sporefall",names={enUS="Sporefall", zhCN="孢陨幽境", zhTW="孢殞幽境"},aliases={"sporefall", "Sporefall", "孢陨幽境", "孢殞幽境"},
      bosses={
        {id=3159,slug="rotmire",names={enUS="Rotmire", zhCN="腐沼", zhTW="腐沼"}},
      },
    },
  },
}
local ok,reason=API:RegisterDataManifest(manifest)
if not ok then _G.QFXTalentDataLoadError=reason end
